### ISSUE TITLE
Downloading data for PJM throws ` JSONDecodeError`

### ISSUE THREAD

**Issue by petervanya** [kmax12/gridstatus#350] opened 2024-03-04 16:12 UTC
A few days ago I started getting an error from running a simple code to download data for PJM. I am using Windows 10 Pro; interestingly, on my personal Mac I do not get this error, which is very strange. Could you please advise how to fix it?

I am running gridstatus version 0.24.0 (also tried 0.26.0, no difference).

Code:
```python
import gridstatus
iso = gridstatus.PJM()

iso.get_pnode_ids() # also iso.get_fuel_mix('today')
```

Error:
```python
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\models.py:971](---LocalCache/local-packages/Python311/site-packages/requests/models.py:971), in Response.json(self, **kwargs)
    [970](---LocalCache/local-packages/Python311/site-packages/requests/models.py:970) try:
--> [971](---LocalCache/local-packages/Python311/site-packages/requests/models.py:971)     return complexjson.loads(self.text, **kwargs)
    [972](---LocalCache/local-packages/Python311/site-packages/requests/models.py:972) except JSONDecodeError as e:
    [973](---LocalCache/local-packages/Python311/site-packages/requests/models.py:973)     # Catch JSON-related errors and raise as requests.JSONDecodeError
    [974](---LocalCache/local-packages/Python311/site-packages/requests/models.py:974)     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError

File [C:\Program](file:///C:/Program) Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    [343](file:///C:/Program%20Files/WindowsApps/PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0/Lib/json/__init__.py:343) if (cls is None and object_hook is None and
    [344](file:///C:/Program%20Files/WindowsApps/PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0/Lib/json/__init__.py:344)         parse_int is None and parse_float is None and
    [345](file:///C:/Program%20Files/WindowsApps/PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0/Lib/json/__init__.py:345)         parse_constant is None and object_pairs_hook is None and not kw):
--> [346](file:///C:/Program%20Files/WindowsApps/PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0/Lib/json/__init__.py:346)     return _default_decoder.decode(s)
    [347](file:///C:/Program%20Files/WindowsApps/PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0/Lib/json/__init__.py:347) if cls is None:

File [C:\Program](file:///C:/Program) Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py:337, in JSONDecoder.decode(self, s, _w)
    [333](file:///C:/Program%20Files/WindowsApps/PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0/Lib/json/decoder.py:333) """Return the Python representation of ``s`` (a ``str`` instance
    [334](file:///C:/Program%20Files/WindowsApps/PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0/Lib/json/decoder.py:334) containing a JSON document).
    [335](file:///C:/Program%20Files/WindowsApps/PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0/Lib/json/decoder.py:335) 
    [336](file:///C:/Program%20Files/WindowsApps/PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0/Lib/json/decoder.py:336) """
--> [337](file:///C:/Program%20Files/WindowsApps/PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0/Lib/json/decoder.py:337) obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    [338](file:///C:/Program%20Files/WindowsApps/PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0/Lib/json/decoder.py:338) end = _w(s, end).end()

File [C:\Program](file:///C:/Program) Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    [354](file:///C:/Program%20Files/WindowsApps/PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0/Lib/json/decoder.py:354) except StopIteration as err:
--> [355](file:///C:/Program%20Files/WindowsApps/PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0/Lib/json/decoder.py:355)     raise JSONDecodeError("Expecting value", s, err.value) from None
    [356](file:///C:/Program%20Files/WindowsApps/PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0/Lib/json/decoder.py:356) return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

JSONDecodeError                           Traceback (most recent call last)
Cell In[4], [line 1](vscode-notebook-cell:?execution_count=4&line=1)
----> [1](vscode-notebook-cell:?execution_count=4&line=1) nodes = iso.get_pnode_ids()

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gridstatus\pjm.py:601](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:601), in PJM.get_pnode_ids(self)
    [595](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:595) def get_pnode_ids(self):
    [596](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:596)     data = {
    [597](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:597)         "fields": "effective_date,pnode_id,pnode_name,pnode_subtype,pnode_type\
    [598](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:598)             ,termination_date,voltage_level,zone",
    [599](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:599)         "termination_date": "12/31/9999exact",
    [600](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:600)     }
--> [601](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:601)     nodes = self._get_pjm_json("pnode", start=None, params=data)
    [603](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:603)     # only keep most recent effective date for each id
    [604](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:604)     # return sorted by pnode_id
    [605](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:605)     nodes = (
    [606](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:606)         nodes.sort_values("effective_date", ascending=False)
    [607](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:607)         .drop_duplicates(
   (...)
    [611](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:611)         .reset_index(drop=True)
    [612](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:612)     )

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gridstatus\pjm.py:887](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:887), in PJM._get_pjm_json(self, endpoint, start, params, end, start_row, row_count, interval_duration_min, verbose)
    [884](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:884) log(msg, verbose)
    [886](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:886) api_key = self._get_key()
--> [887](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:887) r = self._get_json(
    [888](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:888)     "https://api.pjm.com/api/v1/" + endpoint,
    [889](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:889)     params=final_params,
    [890](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:890)     headers={"Ocp-Apim-Subscription-Key": api_key},
    [891](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:891) )
    [893](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:893) if "errors" in r:
    [894](---LocalCache/local-packages/Python311/site-packages/gridstatus/pjm.py:894)     raise RuntimeError(r["errors"])

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gridstatus\base.py:77](---LocalCache/local-packages/Python311/site-packages/gridstatus/base.py:77), in ISOBase._get_json(self, *args, **kwargs)
     [74](---LocalCache/local-packages/Python311/site-packages/gridstatus/base.py:74)     log(msg, verbose)
     [76](---LocalCache/local-packages/Python311/site-packages/gridstatus/base.py:76) r = requests.get(*args, **kwargs)
---> [77](---LocalCache/local-packages/Python311/site-packages/gridstatus/base.py:77) r = r.json()
     [79](---LocalCache/local-packages/Python311/site-packages/gridstatus/base.py:79) return r

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\models.py:975](---LocalCache/local-packages/Python311/site-packages/requests/models.py:975), in Response.json(self, **kwargs)
    [971](---LocalCache/local-packages/Python311/site-packages/requests/models.py:971)     return complexjson.loads(self.text, **kwargs)
    [972](---LocalCache/local-packages/Python311/site-packages/requests/models.py:972) except JSONDecodeError as e:
    [973](---LocalCache/local-packages/Python311/site-packages/requests/models.py:973)     # Catch JSON-related errors and raise as requests.JSONDecodeError
    [974](---LocalCache/local-packages/Python311/site-packages/requests/models.py:974)     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
--> [975](---LocalCache/local-packages/Python311/site-packages/requests/models.py:975)     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by petervanya** [comment] 2024-03-05 15:35
I will investigate the network aspects in more detail, if you could please give me a few days.

**Comment by WillKoehrsen** [comment] 2024-05-06 19:45
Closing due to lack of updates and inability to recreate. Feel free to re-open if this issue re-occurs.

**Closed by WillKoehrsen** 2024-05-06 19:45 UTC

**Comment by petervanya** [comment] 2024-05-09 22:10
@WillKoehrsen apologies for delayed response, took me some time to get to the bottom of this on Windows. I realised that the error was on the side of the connection, that is mine. However, I only figured this out after modifying the code with some warnings pointing at empty dicts. Hence, I would suggest adding some warnings in case no data is downloaded from the API (in my case the PJM).

**Comment by WillKoehrsen** [comment] 2024-05-09 22:12
Thanks for the follow-up! I agree that we could do a better job of showing useful error messages to users, especially when the problem is a lack of data.
